'use server'

import { db } from '@/lib/db';
import { generateToken } from '@/lib/utils';
import { hashPassword } from '@/lib/auth';
import { nanoid } from 'nanoid';
import { revalidatePath } from 'next/cache';
import { SubData } from '@/lib/database/interface';
import { requireAdmin } from '@/lib/admin-guard';
import { tApi } from '@/lib/api-i18n';

// User Management
export async function getUsers(page: number = 1, limit: number = 10, search?: string) {
    await requireAdmin();
    const result = await db.getAllUsers(page, limit, search);

    const usersWithPasskeys = await Promise.all(result.data.map(async (user) => {
        const passkeys = await db.getUserPasskeys(user.id);
        return {
            ...user,
            passkeyCount: passkeys.length
        };
    }));

    return {
        data: usersWithPasskeys,
        total: result.total
    };
}

export async function createUser(formData: FormData) {
    await requireAdmin();
    const username = (formData.get('username') as string)?.trim();
    const password = formData.get('password') as string;
    const nickname = (formData.get('nickname') as string)?.trim();
    const rules = formData.get('customRules') as string;
    const role = (formData.get('role') as string) || 'user';
    const status = 'active';

    if (!username || !password) return { error: 'Missing fields' };

    // Check existing
    if (await db.userExists(username)) {
        return { error: 'User already exists' };
    }

    const hashedPassword = await hashPassword(password);

    // 1. Create User
    await db.setUser(username, {
        id: '', // Will be generated by database
        username,
        password: hashedPassword,
        role,
        status,
        maxSubscriptions: null, // null = follow global settings
        nickname: nickname || undefined,
        createdAt: Date.now(),
        tokenVersion: nanoid(16)
    });

    // Check subscription limit before creating default subscription
    const user = await db.getUser(username);
    if (!user) return { error: 'User creation failed' };
    const config = await db.getGlobalConfig();
    const userLimit = user.maxSubscriptions ?? config.maxUserSubscriptions ?? 10;
    const currentSubs = await db.getUserSubscriptions(user.id);

    if (currentSubs.length >= userLimit) {
        // User created but can't create subscription due to limit
        return { error: 'userCreatedSubLimitExceeded' };
    }

    // Get default or first upstream source
    const upstreamSources = await db.getUpstreamSources();
    let selectedSources: string[] = [];

    if (upstreamSources.length > 0) {
        // Find default source
        const defaultSource = upstreamSources.find(s => s.isDefault);
        if (defaultSource) {
            selectedSources = [defaultSource.name];
        } else {
            // Use first source if no default
            selectedSources = [upstreamSources[0].name];
        }
    }

    // 2. Create Default Subscription
    const token = generateToken();
    const subData: SubData = {
        username,
        remark: await tApi('subscription.defaultSubscription'),
        customRules: rules || '',
        groupId: 'default',
        ruleId: 'default',
        selectedSources, // Only default or first source
        enabled: true,
        createdAt: Date.now()
    };
    await db.createSubscription(token, username, user.id, subData);

    revalidatePath('/admin');
    return { success: true };
}

export async function updateUserStatus(username: string, status: string) {
    await requireAdmin();
    const user = await db.getUser(username);
    if (user) {
        user.status = status;
        await db.setUser(username, user);
        revalidatePath('/admin');
    }
}

export async function updateUserMaxSubscriptions(username: string, maxSubscriptions: number | null) {
    await requireAdmin();
    const user = await db.getUser(username);
    if (user) {
        user.maxSubscriptions = maxSubscriptions;
        await db.setUser(username, user);
        revalidatePath('/admin');
    }
}

export async function updateUser(oldUsername: string, newUsername: string, newPassword?: string, nickname?: string, role?: string) {
    await requireAdmin();
    newUsername = newUsername.trim();
    if (!newUsername) return { error: 'usernameEmpty' };
    const user = await db.getUser(oldUsername);
    if (!user) return { error: 'User not found' };

    // If username changed, rename first (preserves UUID)
    if (oldUsername !== newUsername) {
        if (await db.userExists(newUsername)) {
            return { error: 'newUsernameExists' };
        }
        await db.renameUser(oldUsername, newUsername);
    }

    // Update password/nickname/role fields
    if (newPassword) {
        user.password = await hashPassword(newPassword);
        user.tokenVersion = nanoid(16);
    }
    if (role) {
        user.role = role;
    }
    user.nickname = nickname || undefined;
    user.username = newUsername;
    await db.setUser(newUsername, user);

    // Invalidate sessions if password changed
    if (newPassword) {
        await Promise.all([
            db.deleteAllUserSessions(user.id),
            db.deleteAllUserRefreshTokens(user.id)
        ]);
    }

    revalidatePath('/admin');
    revalidatePath('/dashboard');
    return { success: true };
}

export async function deleteUser(username: string) {
    await requireAdmin();
    const user = await db.getUser(username);
    if (user) {
        // Delete all subscriptions for this user first
        const userSubs = await db.getUserSubscriptions(user.id);
        for (const sub of userSubs) {
            await db.deleteSubscription(sub.token, user.id);
        }

        // Delete avatar if exists
        if (user.avatar) {
            try {
                const { StorageFactory } = await import('@/lib/storage');
                const storage = await StorageFactory.createFromGlobalConfig();
                await storage.delete(user.avatar);
            } catch (error) {
                console.warn('Failed to delete user avatar:', error);
            }
        }

        // Delete all sessions and refresh tokens
        await Promise.all([
            db.deleteAllUserSessions(user.id),
            db.deleteAllUserRefreshTokens(user.id)
        ]);
    }

    // Then delete the user
    await db.deleteUser(username);
    revalidatePath('/admin/users');
}

export async function adminUploadAvatar(formData: FormData) {
    await requireAdmin();
    const username = formData.get('username') as string;
    const file = formData.get('avatar') as File;

    if (!username || !file) {
        return { error: 'Missing required fields' };
    }

    // Check file size (10MB)
    if (file.size > 10 * 1024 * 1024) {
        return { error: 'fileTooLarge' };
    }

    // Check file type
    if (!file.type.startsWith('image/')) {
        return { error: 'imageOnly' };
    }

    try {
        // Convert file to buffer
        const arrayBuffer = await file.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);

        // Validate and process image
        const { ImageProcessor } = await import('@/lib/image-processor');
        const isValid = await ImageProcessor.validateImage(buffer);
        if (!isValid) {
            return { error: 'invalidImage' };
        }

        // Process image (resize to 500x500, convert to WebP)
        const processedBuffer = await ImageProcessor.processAvatar(buffer, 500);

        // Get user
        const user = await db.getUser(username);
        if (!user) {
            return { error: 'userNotFound' };
        }

        // Delete old avatar if exists
        if (user.avatar) {
            try {
                const { StorageFactory } = await import('@/lib/storage');
                const storage = await StorageFactory.createFromGlobalConfig();
                await storage.delete(user.avatar);
            } catch (error) {
                console.warn('Failed to delete old avatar:', error);
            }
        }

        // Upload new avatar
        const { StorageFactory } = await import('@/lib/storage');
        const storage = await StorageFactory.createFromGlobalConfig();
        const avatarUrl = await storage.upload(
            processedBuffer,
            `${user.id}-${Date.now()}`,
            'image/webp'
        );

        // Update user avatar in database
        await db.setUser(username, {
            ...user,
            avatar: avatarUrl,
        });

        revalidatePath('/admin/users');
        return { success: true, avatarUrl };
    } catch (error) {
        console.error('Admin avatar upload error:', error);
        return { error: 'uploadFailed' };
    }
}

export async function adminDeleteAvatar(username: string) {
    await requireAdmin();
    // Get user
    const user = await db.getUser(username);
    if (!user) {
        return { error: 'userNotFound' };
    }

    if (!user.avatar) {
        return { error: 'userNoAvatar' };
    }

    try {
        // Delete avatar from storage
        const { StorageFactory } = await import('@/lib/storage');
        const storage = await StorageFactory.createFromGlobalConfig();
        await storage.delete(user.avatar);
    } catch (error) {
        console.warn('Failed to delete avatar from storage:', error);
    }

    // Update user avatar in database
    await db.setUser(username, {
        ...user,
        avatar: undefined,
    });

    revalidatePath('/admin/users');
    return { success: true };
}

export async function resetUser2FA(username: string) {
    await requireAdmin();
    const user = await db.getUser(username);
    if (!user) {
        return { error: 'userNotFound' };
    }

    await db.setUser(username, {
        ...user,
        totpEnabled: false,
        totpSecret: undefined,
    });

    revalidatePath('/admin/users');
    return { success: true };
}

export async function adminGetUserPasskeys(userId: string) {
    await requireAdmin();
    try {
        const passkeys = await db.getUserPasskeys(userId);
        return { success: true, passkeys };
    } catch (error) {
        console.error('Failed to fetch user passkeys:', error);
        return { error: 'getPasskeysFailed' };
    }
}

export async function adminDeletePasskey(passkeyId: string, userId: string) {
    await requireAdmin();
    try {
        await db.deletePasskey(passkeyId, userId);
        revalidatePath('/admin/users');
        return { success: true };
    } catch (error) {
        console.error('Failed to delete passkey:', error);
        return { error: 'deletePasskeyFailed' };
    }
}

export async function adminGetUserOAuthBindings(userId: string) {
    await requireAdmin();
    try {
        const bindings = await db.getUserOAuthBindings(userId);
        const providers = await db.getOAuthProviders();
        const enriched = bindings.map(binding => {
            const provider = providers.find(p => p.id === binding.providerId);
            return {
                ...binding,
                providerName: provider?.name || 'Unknown',
                providerType: provider?.type || 'custom',
                providerIcon: provider?.icon
            };
        });
        return { success: true, bindings: enriched };
    } catch (error) {
        console.error('Failed to fetch user OAuth bindings:', error);
        return { error: 'getOAuthBindingsFailed' };
    }
}

export async function adminDeleteOAuthBinding(bindingId: string) {
    await requireAdmin();
    try {
        await db.deleteOAuthBinding(bindingId);
        revalidatePath('/admin/users');
        return { success: true };
    } catch (error) {
        console.error('Failed to delete OAuth binding:', error);
        return { error: 'deleteOAuthBindingFailed' };
    }
}
